[package]
name = "df_extension_types"
version.workspace = true
edition.workspace = true

[dependencies]
arrow.workspace = true
arrow-schema.workspace = true
datafusion.workspace = true
tokio.workspace = true
uuid.workspace = true
